const options = [
    "powerbi",
    "bipower",
    "erp",
    "feg",
    "old",
    "fegerp",
    "zendeskmanager",
    "managerzendesk",
    "knowledgebase",
    "baseknowledge",
    "createticket",
    "ticketcreate",
    "calendar",
    "forum",
    "fegbook",
    "paylocity",
    "locity",
    "company",
    "announcement",
    "company calendar",
    "website",
    "plataforms",
    "debitcard",
    "card",
    "netsuite",
    "oracle",
    "schoox",
    "voya",
    "financial",
    "blue",
    "bluecross",
    "blueshield",
    "cross",
    "shield",
    "guardian",
    "life", 
    "insurance",
]

export default options